session_timeout:
    timeout: null

chip.channel.www_server:
    connections:
        - port: 8080
        - routes:
             cors:
                 additionalHeaders: ["Access-Control-Allow-Headers"]
